"""Create user table

Revision ID: 996dae0cdde4
Revises: c201726fb055
Create Date: 2025-04-30 11:08:52.834744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996dae0cdde4'
down_revision: Union[str, None] = 'c201726fb055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed dropping of error_images and error tables to avoid dependency errors
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], name='error_images_error_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='error_images_pkey')
    )
    op.create_table('error',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='error_pkey')
    )
    op.create_index('ix_error_name', 'error', ['name'], unique=False)
    # ### end Alembic commands ###
