"""Remove role and admin_logs from User model

Revision ID: b6aab058c033
Revises: f663919fd8ac
Create Date: 2025-04-30 10:46:59.642772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6aab058c033'
down_revision: Union[str, None] = 'f663919fd8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_images')
    op.drop_index('ix_error_name', table_name='error')
    op.drop_table('error')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('error_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='error_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_error_name', 'error', ['name'], unique=False)
    op.create_table('error_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], name='error_images_error_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='error_images_pkey')
    )
    # ### end Alembic commands ###
