version: '3.8'

services:
  api:
    image: goga11112/fastapi-errors-api:latest
    container_name: fastapi_api
    ports:
      - "8000:8000"
    environment:
      UPLOAD_DIR: /app/uploaded_images
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db_errors
      SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImV4cCI6MTc0NTIxOTUyNX0.-sjuDM9hG-3-c46EGUe2g0UDRWDIBnoAYZdBE5Ohdeg
      POSTGRES_HOST: db
      POSTGRES_DB: db_errors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: goga11112/fastapi-errors-frontend:latest
    container_name: fastapi_frontend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - api
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: fastapi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_errors
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastapi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
    name: fastapi_pgdata
  uploaded_images:
    name: fastapi_uploaded_images
  pgadmindata:
