version: '3.8'

services:
  api:
    build:
      context: ./app
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./uploaded_images:/app/uploaded_images
    environment:
      - UPLOAD_DIR=/app/uploaded_images
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db_errors
    depends_on: 
      - db

  frontend:
    build:
      context: ./frontend
    container_name: fastapi_frontend
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - api

  db:
    image: postgres:15
    container_name: fastapi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_errors
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmindata:
  frontend_node_modules:
